services:
  local:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
